export const GET_TIMESHEET_DATA = "GET_TIMESHEET_DATA";
export const GET_EMPLOYEE_DATA = "GET_EMPLOYEE_DATA";
export const UPDATE_TIMESHEET_DATA = "UPDATE_TIMESHEET_DATA";
export const GET_EVENT_DATA = "GET_EVENT_DATA";
export const GET_LOGIN_DATA = "GET_LOGIN_DATA";